namespace: epfl_si
name: python3
version: 0.1.0

readme: README.md

authors:
- EPFL ISAS-FSD <isas-fsd@groupes.epfl.ch>

description: Install Python 3 through pyenv to remote nodes. No root required.

license:
- GPL-2.0-or-later

tags:
  - pyenv
  - no-root

dependencies: {}

repository: https://github.com/epfl-si/ansible-collection-python3
